/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_HelloWorldJNI */

#ifndef _Included_org_example_HelloWorldJNI
#define _Included_org_example_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
