/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ExampleOpenSSL */

#ifndef _Included_org_example_ExampleOpenSSL
#define _Included_org_example_ExampleOpenSSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ExampleOpenSSL
 * Method:    generateKeyPair
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_example_ExampleOpenSSL_generateKeyPair
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ExampleOpenSSL
 * Method:    encryptData
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_example_ExampleOpenSSL_encryptData
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     org_example_ExampleOpenSSL
 * Method:    decryptData
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_example_ExampleOpenSSL_decryptData
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
