/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ExampleFileIO */

#ifndef _Included_org_example_ExampleFileIO
#define _Included_org_example_ExampleFileIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ExampleFileIO
 * Method:    readLargeFile
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_example_ExampleFileIO_readLargeFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_example_ExampleFileIO
 * Method:    writeProcessedData
 * Signature: (Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_org_example_ExampleFileIO_writeProcessedData
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
