/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ExampleCSVParser */

#ifndef _Included_org_example_ExampleCSVParser
#define _Included_org_example_ExampleCSVParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ExampleCSVParser
 * Method:    parseCSVFile
 * Signature: (Ljava/lang/String;)[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_example_ExampleCSVParser_parseCSVFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
