/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ExampleObjectsJNI */

#ifndef _Included_org_example_ExampleObjectsJNI
#define _Included_org_example_ExampleObjectsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ExampleObjectsJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lorg/example/model/UserData;
 */
JNIEXPORT jobject JNICALL Java_org_example_ExampleObjectsJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     org_example_ExampleObjectsJNI
 * Method:    printUserData
 * Signature: (Lorg/example/model/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_ExampleObjectsJNI_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
