/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ExampleMatrixJNI */

#ifndef _Included_org_example_ExampleMatrixJNI
#define _Included_org_example_ExampleMatrixJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ExampleMatrixJNI
 * Method:    multiplyMatrix
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_example_ExampleMatrixJNI_multiplyMatrix
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
